# Generated by Django 4.0 on 2022-03-10 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_details', models.CharField(max_length=500, verbose_name='Earning Details')),
                ('earning_amount', models.IntegerField(verbose_name='Earning Amount')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_details', models.CharField(max_length=500)),
                ('invest_amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Upsteam_deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upsteam_deal', models.FloatField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Yearly_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.IntegerField()),
                ('invoice_details', models.CharField(max_length=500)),
                ('Staffs_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffs')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.year')),
            ],
        ),
        migrations.CreateModel(
            name='Yearly_Earn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.IntegerField()),
                ('invoice_details', models.CharField(max_length=500)),
                ('Staffs_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffs')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.year')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.IntegerField()),
                ('invoice_details', models.CharField(max_length=500)),
                ('Staffs_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffs')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.year')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Earn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.IntegerField()),
                ('invoice_details', models.CharField(max_length=500)),
                ('Staffs_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffs')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.year')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.IntegerField()),
                ('invoice_details', models.CharField(max_length=500)),
                ('Staffs_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffs')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.year')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Earn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.IntegerField()),
                ('invoice_details', models.CharField(max_length=500)),
                ('Staffs_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffs')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.year')),
            ],
        ),
    ]
