# Generated by Django 4.0 on 2022-03-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_id', models.IntegerField(default=7100)),
            ],
        ),
        migrations.CreateModel(
            name='Resellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=245)),
                ('commission', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=245)),
                ('rid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resellers.resellerid')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resellers_Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commission_amount', models.FloatField(default=0.0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.month')),
                ('resellerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resellers.resellers', verbose_name='Reseller Name')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.year')),
            ],
        ),
    ]
