# Generated by Django 4.0 on 2022-03-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_email_alter_clients_olt_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='nid',
            field=models.CharField(max_length=11),
        ),
    ]
